apiVersion: apps/v1
kind: Deployment
metadata:
  name: Footballer
spec:
  selector:
    matchLabels:
      app: Footballer
  replicas: 1
  template:
    metadata:
      labels:
        app: Footballer
    spec:
      containers:
        - name: Footballer
          image: footballer.jar:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi